stages:
  preprocess:
    cmd: python .\src\preprocess.py
    deps:
      - src/preprocess.py
      - data/train.csv
      - params.yaml
    outs:
      - config.ini
      - data/train_split.csv
      - data/val_split.csv

  train:
    cmd: python .\src\train.py
    deps:
      - src/train.py
      - src/logger.py
      - data/train_split.csv
      - data/val_split.csv
      - params.yaml
    outs:
      - experiments/tfidf_log_reg.pkl
    metrics:
      - experiments/metrics.json:
          cache: false

  predict:
    cmd: python .\src\predict.py --output .\experiments\submission.csv
    deps:
      - src/predict.py
      - src/logger.py
      - data/test.csv
      - experiments/tfidf_log_reg.pkl
    outs:
      - experiments/submission.csv
